export function generateClassReportPDF(classData: any) {
  const { className, summary, students } = classData
  
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-KE', {
      style: 'currency',
      currency: 'KES'
    }).format(amount)
  }

  const formatDate = (date: string | null) => {
    if (!date) return 'Never'
    return new Date(date).toLocaleDateString('en-KE')
  }

  return `
  <!DOCTYPE html>
  <html>
  <head>
    <title>Class Fee Report - ${className}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 20px; font-size: 12px; }
      .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1e40af; padding-bottom: 20px; }
      .school-name { color: #1e40af; font-size: 24px; font-weight: bold; margin: 0; }
      .report-title { color: #666; font-size: 18px; margin: 5px 0; }
      .class-name { color: #1e40af; font-size: 20px; font-weight: bold; margin: 10px 0; }
      .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0; }
      .summary-card { background: #f8f9fa; border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px; text-align: center; }
      .summary-card h3 { margin: 0; color: #374151; font-size: 14px; }
      .summary-card p { margin: 5px 0 0 0; font-size: 18px; font-weight: bold; color: #1e40af; }
      .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
      .table th, .table td { padding: 8px; border: 1px solid #e5e7eb; text-align: left; font-size: 11px; }
      .table th { background: #f8f9fa; font-weight: bold; }
      .table tbody tr:nth-child(even) { background: #f9fafb; }
      .status-paid-full { background: #d1fae5; color: #059669; padding: 2px 6px; border-radius: 4px; font-size: 10px; }
      .status-partial { background: #fef3c7; color: #d97706; padding: 2px 6px; border-radius: 4px; font-size: 10px; }
      .status-unpaid { background: #fee2e2; color: #dc2626; padding: 2px 6px; border-radius: 4px; font-size: 10px; }
      .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #666; font-size: 10px; }
      .text-green { color: #059669; }
      .text-red { color: #dc2626; }
      @media print { body { margin: 0; font-size: 10px; } }
    </style>
  </head>
  <body>
    <div class="header">
      <h1 class="school-name">St. Joseph's Academy</h1>
      <h2 class="report-title">Class Fee Report</h2>
      <h3 class="class-name">${className}</h3>
      <p>Generated on ${new Date().toLocaleDateString('en-KE')}</p>
    </div>

    <div class="summary-grid">
      <div class="summary-card">
        <h3>Total Students</h3>
        <p>${summary.totalStudents}</p>
      </div>
      <div class="summary-card">
        <h3>Paid in Full</h3>
        <p class="text-green">${summary.paidInFull}</p>
      </div>
      <div class="summary-card">
        <h3>Outstanding</h3>
        <p class="text-red">${summary.unpaid + summary.partialPayment}</p>
      </div>
      <div class="summary-card">
        <h3>Total Outstanding</h3>
        <p class="text-red">${formatCurrency(summary.totalOutstanding)}</p>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Adm. No.</th>
          <th>Student Name</th>
          <th>Total Due</th>
          <th>Paid</th>
          <th>Balance</th>
          <th>Status</th>
          <th>Last Payment</th>
        </tr>
      </thead>
      <tbody>
        ${students.map((student: any) => `
          <tr>
            <td>${student.admissionNumber}</td>
            <td>${student.firstName} ${student.lastName}</td>
            <td>${formatCurrency(student.totalDue)}</td>
            <td class="text-green">${formatCurrency(student.totalPaid)}</td>
            <td class="text-red">${formatCurrency(student.totalBalance)}</td>
            <td><span class="status-${student.status.toLowerCase().replace('_', '-')}">${student.status.replace('_', ' ')}</span></td>
            <td>${formatDate(student.lastPaymentDate)}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <div class="footer">
      <p>This report contains ${summary.totalStudents} students with total outstanding fees of ${formatCurrency(summary.totalOutstanding)}</p>
      <p>Report generated by St. Joseph's Academy Fee Management System</p>
    </div>
  </body>
  </html>
  `
}